accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
app_name = 'accounts'
urlpatterns = [
 path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'),
name='login'),
 path('logout/', auth_views.LogoutView.as_view(), name='logout'),
 path('signup/', views.signup, name='signup'),
]

my_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mysite/', include('mysite.urls')),
    path('', include('pages.urls')),
    path('accounts/', include('accounts.urls')),
]

mysite/urls.py
from django.urls import path

from.import views


urlpatterns = [
    path('', views.index),
    path('<int:content_id>/', views.detail, name='detail'),
    path('comment/create/<int:content_id>/', views.comment_create, name='comment_create'),
    path('comment/update/<int:comment_id>/', views.comment_update, name='comment_update'),
    path('comment/delete/<int:comment_id>/', views.comment_delete, name='comment_delete'),
]

pages/urls.py
from django.urls import path

from.import views


urlpatterns = [
    path('', views.mainpage),
    path('company/', views.company),
    path('news/', views.news),
    path('product_all/', views.product_all),
    path('product_detail/', views.product_detail),
    path('newProduct1/', views.newProduct1),
    path('newProduct2/', views.newProduct2),
    path('newProduct3/', views.newProduct3),
    path('ToS/', views.ToS),
    path('privacy_policy/', views.privacy_policy),
]

accounts/models.py
from django.db import models

# Create your models here.

mysite/models.py
from django.db import models
from django.contrib.auth.models import User

class MainContent(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.title

class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content_list = models.ForeignKey(MainContent, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField(auto_now_add=True)
    modify_date = models.DateTimeField(auto_now=True)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
class SignupForm(UserCreationForm):
 email = forms.EmailField()
 class Meta:
  model = User
  fields = ("username", "password1", "password2", "email")

mysite/forms.py
from .models import Comment
from django import forms

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)

accounts/views.py
from django.contrib.auth import login
from django.shortcuts import render, redirect
from accounts.forms import SignupForm
def signup(request):
 if request.method == "POST":
  form = SignupForm(request.POST)
  if form.is_valid():
   user = form.save()
   login(request, user)
   return redirect('/')
 else:
  form = SignupForm()
 return render(request, 'accounts/signup.html', {'form': form})

mysite/views.py
from django.core.exceptions import PermissionDenied
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required
from.models import MainContent, Comment
from.forms import CommentForm

def index(request):
    content_list = MainContent.objects.order_by('-pub_date')
    context = {'content_list':content_list}
    return render(request, 'mysite/content_list.html', context)

def detail(request, content_id):
    content_list = MainContent.objects.get(id=content_id)
    context = {'content_list': content_list}
    return render(request, 'mysite/content_detail.html', context)

@login_required(login_url='accounts:login')
def comment_create(request, content_id):
    content_list = get_object_or_404(MainContent, pk=content_id)

    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.content_list = content_list
            comment.author = request.user
            comment.save()
            return redirect('detail', content_id=content_list.id)
    else:
        form = CommentForm()

    context = {'content_list': content_list, 'form': form}
    return render(request, 'mysite/content_detail.html', context)

@login_required(login_url='accounts:login')
def comment_update(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)

    if request.user != comment.author:
        raise PermissionDenied

    if request.method == 'POST':
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.save()
            return redirect('detail', content_id=comment.content_list.id)
    else:
        form = CommentForm(instance=comment)

    context = {'comment': comment, 'form': form}
    return render(request, 'mysite/comment_form.html', context)

@login_required(login_url='accounts:login')
def comment_delete(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)

    if request.user != comment.author:
        raise PermissionDenied
    else:
        comment.delete()
    return redirect('detail', content_id=comment.content_list.id)

pages/views.py
from django.shortcuts import render

def mainpage(request): # 홈 메인
    return render(request, 'pages/mainpage.html')

def company(request): # 회사소개
    return render(request, 'pages/company_info.html')

def news(request): # 소식
    return render(request, 'pages/news.html')

def product_all(request): # 전체 상품
    return render(request, 'pages/product_all.html')

def product_detail(request): # 상품 상세정보
    return render(request, 'pages/product_detail.html')

def newProduct1(request): # 전체 상품
    return render(request, 'pages/newProduct1.html')

def newProduct2(request): # 전체 상품
    return render(request, 'pages/newProduct2.html')

def newProduct3(request): # 전체 상품
    return render(request, 'pages/newProduct3.html')

def ToS(request): # 전체 상품
    return render(request, 'pages/ToS.html')

def privacy_policy(request): # 전체 상품
    return render(request, 'pages/privacy_policy.html')

templates/accounts/login.html
{% extends "base.html" %}
{% block content %}
{% if form.errors %}
<p>아이디 또는 비밀번호가 틀립니다. 다시 시도해주세요.</p>
{% endif %}
<form method="post" action="{% url 'accounts:login' %}">
{% csrf_token %}
<table>
<tr>
 <td>{{ form.username.label_tag }}</td>
 <td>{{ form.username }}</td>
</tr>
<tr>
 <td>{{ form.password.label_tag }}</td>
 <td>{{ form.password }}</td>
</tr>
</table>
<input type="submit" value="login">
</form>
<a href="{% url 'accounts:signup' %}">signup</a>
{% endblock %}

<section class="page-section" id="contact">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-lg-8 col-xl-6 text-center">
                        <h2 class="mt-0">로그인</h2>
                        <hr class="divider" />
                        <p class="text-muted mb-5">아이디와 비밀번호를 입력해주세요.</p>
                    </div>
                </div>
                <div class="row gx-4 gx-lg-5 justify-content-center mb-5">
                    <div class="col-lg-6">
                        <form id="login" data-sb-form-api-token="API_TOKEN">
                            <!-- 아이디 입력-->
                            <div class="form-floating mb-3">
                                <input class="form-control" id="id" type="text" placeholder="Enter your id..." data-sb-validations="required" />
                                <label for="id">아이디</label>
                                <div class="invalid-feedback" data-sb-feedback="id:required">id is required.</div>
                            </div>
                            <!-- 비밀번호 입력-->
                            <div class="form-floating mb-3">
                                <input class="form-control" id="pw" type="password" placeholder="Enter your password..." data-sb-validations="required" />
                                <label for="pw">비밀번호</label>
                                <div class="invalid-feedback" data-sb-feedback="pw:required">password is required.</div>
                                <!--<div class="invalid-feedback" data-sb-feedback="email:email">Email is not valid.</div>-->
                            </div>
                            <!-- success message-->
                            <div class="d-none" id="loginSuccessMessage">
                                <div class="text-center mb-3">
                                    <div class="fw-bolder">successful!</div>
                                </div>
                            </div>
                            <!-- error message-->
                            <div class="d-none" id="loginErrorMessage"><div class="text-center text-danger mb-3">Error!</div></div>
                            <!-- login Button-->
                            <div class="d-grid"><button class="btn btn-primary btn-xl disabled" login="loginButton" type="button">login</button></div>
                            <!-- 회원가입 / 아이디, 비밀번호 찾기-->
                            <hr class="divider" />
                            <a class="btn btn-primary" href="http://localhost:8000/join/">회원가입</a>
                            <a class="btn btn-primary" href="http://localhost:8000/findID/">아이디 찾기</a>
                            <a class="btn btn-primary" href="http://localhost:8000/findPW/">비밀번호 재설정</a>
                        </form>
                    </div>
                </div>
            </div>
        </section>

templates/accounts/signup.html
{% extends 'base.html' %}
{% block content %}
 <h2>Sign up</h2>
 <form method="post">
 {% csrf_token %}
 {{ form.as_p }}
 <button type="submit">Sign Up</button>
 </form>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Seongwon's Comento project</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Bootstrap Icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css" />
        <!-- SimpleLightbox plugin CSS-->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    </head>
    <body>
        {% include "navbar.html" %}
        {% block content %}
        {% endblock %}
        {% include "footer.html" %}
    </body>

templates/footer.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Seongwon's Comento project</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Bootstrap Icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css" />
        <!-- SimpleLightbox plugin CSS-->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    </head>
    <body>
        <!-- Footer-->
        <footer class="bg-light py-5">
            <a class="btn btn-dark btn-xl" href="http://localhost:8000/ToS/">이용약관</a>
            <a class="btn btn-dark btn-xl" href="http://localhost:8000/privacy_policy/">개인정보처리방침</a>
            <div class="container px-4 px-lg-5"><div class="small text-center text-muted">회사부가정보 / Copyright &copy; 2021 - Company Name</div></div>
        </footer>
    </body>

templates/mysite/comment_form.html
{% extends 'base.html' %}
{% block content %}
<h2> update comment</h2>
<section class="mb-5">
    <div class="card bg-light">
        <div class="card-body">
            <form method="post" class="mb-4" action="{% url 'comment_update' comment.id %}">
                {% csrf_token %}
                <textarea id="content" name="content" class="form-control" rows="3">{{ form.content.value }}</textarea>
                <button type="submit" class="btn btn-primary">submit</button>
            </form>
        </div>
    </div>
</section>
{% endblock %}

templates/mysite/content_detail.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends 'base.html' %}
{% block content %}
<h2>{{ content_list.title }}</h2>
<div>
    {{ content_list.content }}
</div>
<section class="mb-5">
    <div class="card bg-light">
        <div class="card-body">
            <form method="post" class="mb-4" action="{% url 'comment_create' content_list.id %}">
                {% csrf_token %}
                <textarea id="content" name="content" class="form-control" rows="3" placeholder="내용을 입력해주세요."></textarea>
                <button type="submit" class="btn btn-primary">submit</button>
            </form>
            {% for comment in content_list.comment_set.all %}
            <div class="d-flex">
                <div class="ms-3">
                    <div class="fw-bold">{{ comment.author.username }} &nbsp {{ comment.create_date }}
                        {% if comment.create_date != comment.modify_date %}
                        / 수정일자: {{ comment.modify_date }}
                        {% endif %}
                        {% if request.user == comment.author %}
                            <a href="{% url 'comment_update' comment.id %}" class="btn btn-sm btn-outlinesecondary">수정</a>
                            <a href="{% url 'comment_delete' comment.id %}" class="btn btn-sm btn-outlinesecondary">삭제</a>
                        {% endif %}
                    </div>
                    {{ comment.content }}
                </div>
            </div>
            <br/>
            {% endfor %}
        </div>
    </div>
</section>
{% endblock %}
</body>
</html>

templates/mysite/content_list.html
        {% extends 'base.html' %}
        {% block content %}
        <!-- Masthead-->
        <header class="masthead">
            <div class="container px-4 px-lg-5 h-100">
                <div class="row gx-4 gx-lg-5 h-100 align-items-center justify-content-center text-center">
                    <div class="col-lg-8 align-self-end">
                        <h1 class="text-white font-weight-bold">방문해주셔서 감사합니다.</h1>
                        <hr class="divider" />
                    </div>
                    <div class="col-lg-8 align-self-baseline">
                        <p class="text-white-75 mb-5">코멘토 직무부트캠프 2주차 과제입니다.</p>
                        <a class="btn btn-light btn-xl" href="#상품">신규상품 보기</a>
                    </div>
                </div>
            </div>
        </header>
        <!-- 회사소개-->
        <section class="page-section bg-dark" id="회사소개">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-lg-8 text-center">
                        <h2 class="text-white mt-0">역사 / 경영이념 / 사업 페이지</h2>
                        <hr class="divider divider-light" />
                        <p class="text-white-75 mb-4">아직 페이지가 완성되지 않았습니다.</p>
                    </div>
                </div>
            </div>
        </section>
        <!-- 신규상품-->
        <section class="page-section" id="상품">
            <div class="container px-4 px-lg-5">
                <h2 class="text-center mt-0">신규상품 페이지 입니다.</h2>
                <hr class="divider" />
                <section class="page-section bg-dark" id="신규상품1">
                    <div class="container px-4 px-lg-5">
                        <div class="row gx-4 gx-lg-5 justify-content-center">
                            <div class="col-lg-8 text-center">
                                <h2 class="text-white mt-0">신규상품 1</h2>
                                <hr class="divider divider-light" />
                                <li class="new product1"><a class="link active" href="/mysite/1">신규상품명1</a></li>
                            </div>
                        </div>
                    </div>
                </section>
                <section class="page-section bg-dark" id="신규상품2">
                    <div class="container px-4 px-lg-5">
                        <div class="row gx-4 gx-lg-5 justify-content-center">
                            <div class="col-lg-8 text-center">
                                <h2 class="text-white mt-0">신규상품 2</h2>
                                <hr class="divider divider-light" />
                                <li class="new product1"><a class="link active" href="/mysite/2">신규상품명2</a></li>
                            </div>
                        </div>
                    </div>
                </section>
                <section class="page-section bg-dark" id="신규상품3">
                    <div class="container px-4 px-lg-5">
                        <div class="row gx-4 gx-lg-5 justify-content-center">
                            <div class="col-lg-8 text-center">
                                <h2 class="text-white mt-0">신규상품 3</h2>
                                <hr class="divider divider-light" />
                                <li class="new product1"><a class="link active" href="/mysite/3">신규상품명3</a></li>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </section>
        <!-- 인기상품-->
        <section class="page-section bg-dark text-white">
            <div class="container px-4 px-lg-5 text-center">
                <h2 class="mb-4">인기상품 페이지 입니다.</h2>
                <hr class="divider" />
                <div class="row gx-4 gx-lg-5">
                    {%if content_list%}
                        {%for content in content_list%}
                            <div class="col-lg-4 col-md-6 text-center">
                                <div class="mt-5">
                                    <div class="mb-2"><i class="bi-box fs-1 text-primary"></i></div>
                                    <h3 class="h4 mb-2">{{ content.title }}</h3>
                                    <p>{{ content.content | truncatewords:30 }}</p>
                                    <a class="btn btn-light btn-xl" href="/mysite/{{ content.id }}">자세히 보기</a>
                                </div>
                            </div>
                        {%endfor%}
                    {%endif%}
                    <div class="col-lg-4 col-md-6 text-center">
                        <div class="mt-5">
                            <div class="mb-2"><i class="bi-box fs-1 text-primary"></i></div>
                            <h3 class="h4 mb-2">인기상품_2</h3>
                            <p>{{ content.content | truncatewords:30 }}</p>
                            <a class="btn btn-light btn-xl" href="http://localhost:8000/product_detail/">자세히 보기</a>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-6 text-center">
                        <div class="mt-5">
                            <div class="mb-2"><i class="bi-box fs-1 text-primary"></i></div>
                            <h3 class="h4 mb-2">인기상품_3</h3>
                            <p>{{ content.content | truncatewords:30 }}</p>
                            <a class="btn btn-light btn-xl" href="http://localhost:8000/product_detail/">자세히 보기</a>
                        </div>
                    </div>
                </div>
                <hr class="divider" />
                <a class="btn btn-light btn-xl" href="http://localhost:8000/product_all/">더 많은 상품 보러 가기</a>
            </div>
        </section>
        {% endblock %}

templates/navbar.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Seongwon's Comento project</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Bootstrap Icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css" />
        <!-- SimpleLightbox plugin CSS-->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    </head>
    <body>
        <!-- Responsive navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container px-5">
                <a class="navbar-brand" href="http://localhost:8000/mysite/">seongwon</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item"><a class="nav-link active" href="#회사소개">회사소개</a></li>
                        <li class="nav-item"><a class="nav-link active" href="#상품">상품</a></li>
                        <li class="nav-item"><a class="nav-link active" href="http://localhost:8000/news/">소식</a></li>
                    </ul>
                </div>
                    {% if user.is_authenticated %}
                    <a class="btn btn-light" href="{% url 'accounts:logout' %}">{{ user.username }} / logout</a>
                    {% else %}
                    <a class="btn btn-light" href="{% url 'accounts:login' %}">log in</a>
                    {% endif %}
            </div>
        </nav>
    </body>

templates/pages/ToS.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>이용약관</title>
</head>
<body>

<h1>이용약관 페이지</h1>
</body>
</html>

templates/pages/company_info.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>회사 소개</title>
</head>
<body>
<nav>
    <a href="/company/">company info</a>
    <a href="/mysite/">product</a>
</nav>
{% extends 'base.html' %}
{% block content %}
<h1>회사소개 페이지입니다.</h1>
{% endblock %}
</body>
</html>

templates/pages/login.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
<head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Seongwon's Comento project</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Bootstrap Icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css" />
        <!-- SimpleLightbox plugin CSS-->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
</head>
<body>
<!-- 로그인-->
        <section class="page-section" id="contact">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-lg-8 col-xl-6 text-center">
                        <h2 class="mt-0">로그인</h2>
                        <hr class="divider" />
                        <p class="text-muted mb-5">아이디와 비밀번호를 입력해주세요.</p>
                    </div>
                </div>
                <div class="row gx-4 gx-lg-5 justify-content-center mb-5">
                    <div class="col-lg-6">
                        <form id="login" data-sb-form-api-token="API_TOKEN">
                            <!-- 아이디 입력-->
                            <div class="form-floating mb-3">
                                <input class="form-control" id="id" type="text" placeholder="Enter your id..." data-sb-validations="required" />
                                <label for="id">아이디</label>
                                <div class="invalid-feedback" data-sb-feedback="id:required">id is required.</div>
                            </div>
                            <!-- 비밀번호 입력-->
                            <div class="form-floating mb-3">
                                <input class="form-control" id="pw" type="password" placeholder="Enter your password..." data-sb-validations="required" />
                                <label for="pw">비밀번호</label>
                                <div class="invalid-feedback" data-sb-feedback="pw:required">password is required.</div>
                                <!--<div class="invalid-feedback" data-sb-feedback="email:email">Email is not valid.</div>-->
                            </div>
                            <!-- success message-->
                            <div class="d-none" id="loginSuccessMessage">
                                <div class="text-center mb-3">
                                    <div class="fw-bolder">successful!</div>
                                </div>
                            </div>
                            <!-- error message-->
                            <div class="d-none" id="loginErrorMessage"><div class="text-center text-danger mb-3">Error!</div></div>
                            <!-- login Button-->
                            <div class="d-grid"><button class="btn btn-primary btn-xl disabled" login="loginButton" type="button">login</button></div>
                            <!-- 회원가입 / 아이디, 비밀번호 찾기-->
                            <hr class="divider" />
                            <a class="btn btn-primary" href="http://localhost:8000/join/">회원가입</a>
                            <a class="btn btn-primary" href="http://localhost:8000/findID/">아이디 찾기</a>
                            <a class="btn btn-primary" href="http://localhost:8000/findPW/">비밀번호 재설정</a>
                        </form>
                    </div>
                </div>
            </div>
        </section>
</body>
</html>

templates/pages/mainpage.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>메인 페이지</title>
</head>
<body>
<nav>
    <a href="/company/">company info</a>
    <a href="/mysite/">product</a>
</nav>

<h1>메인 페이지입니다.</h1>
</body>
</html>

templates/pages/navbar.html
<ul class="navbar-nav mb-2 mb-lg-0">
 <li class="nav-item"><a class="nav-link" href="/company/">company info</a></li>
 <li class="nav-item"><a class="nav-link" href="/mysite/">product</a></li>
 {% if user.is_authenticated %}
 <a class="btn btn-light" href="{% url 'accounts:logout' %}">{{ user.username }} / logout</a>
 {% else %}
 <a class="btn btn-light" href="{% url 'accounts:login' %}">log in</a>
 {% endif %}
</ul>

templates/pages/newProduct1.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>신규상품1</title>
</head>
<body>

<h1>신규상품1 상세정보</h1>
</body>
</html>

templates/pages/newProduct2.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>신규상품2</title>
</head>
<body>

<h1>신규상품2 상세정보</h1>
</body>
</html>

templates/pages/newProduct3.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>신규상품3</title>
</head>
<body>

<h1>신규상품3 상세정보</h1>
</body>
</html>

templates/pages/news.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>소식</title>
</head>
<body>

<h1>회사 소식 페이지입니다.</h1>
</body>
</html>

templates/pages/privacy_policy.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>개인정보처리방침</title>
</head>
<body>

<h1>개인정보처리방침 페이지</h1>
</body>
</html>

templates/pages/product_all.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>전체 상품</title>
</head>
<body>

<h1>전체 상품 페이지</h1>
</body>
</html>

templates/pages/product_detail.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>제품 상세정보</title>
</head>
<body>

<h1>제품 상세정보 페이지</h1>
</body>
</html>